### ISSUE TITLE
opal can't find for sprocket c_lexer with js type

### ISSUE THREAD

**Issue by epipheus** [opal/c_lexer#3]
I'm getting `Sprockets::FileNotFound: couldn't find file 'c_lexer' with type 'application/javascript'` in production when upgrading to opal 1.0.0.  I'm trying to track down the issue.

**Comment by elia** [comment]
@epipheus what setup code are you using? Maybe there's something like `use_gem 'opal'` or `append_path 'opal/lib'`?

**Comment by epipheus** [comment]
my assets are gemified, just a simple require "opal"  and the like.  Maybe I'm not answering the question, what am I missing?  What do you need to know to help me diagnose?

**Comment by epipheus** [comment]
It seems to give this error at every place I try using asset path/url helpers

**Comment by epipheus** [comment]
I also get `Sprockets::FileNotFound: couldn't find file 'c_lexer' with type 'application/javascript'
Checked in these paths: ...blah blah...`

during asset precompile

**Comment by elia** [comment]
> Maybe I'm not answering the question, what am I missing?

The best is always to give instruction that will consistently reproduce the problem, so I can analyze is locally, for example a sequence of commands or a repo demonstrating the issue.

**Comment by iliabylich** [comment]
Closing. Feel free to reopen if you have instructions to reproduce the issue.
